$BGCOLOR=rgb(ffffcc)
$FGCOLOR=rgb(5b5b49)
$BORDER_FOCUS=rgba(3a3a2eee)
$BORDER_NORMAL=rgba(9c9c7dee)

$BLACK=rgba(ffffccee)
$RED=rgba(ffbfa5ee)
$GREEN=rgba(e7ff99ee)
$YELLOW=rgba(fff299ee)
$BLUE=rgba(bfbfd9ee)
$PURPLE=rgba(f2bfd9ee)
$AQUA=rgba(bfffc5ee)
$GRAY=rgba(9c9c7dee)
$BRGRAY=rgba(7c7c63ee)
$BRRED=rgba(ffbfa5ee)
$BRGREEN=rgba(e7ff99ee)
$BRYELLOW=rgba(fff299ee)
$BRBLUE=rgba(bfbfd9ee)
$BRPURPLE=rgba(f2bfd9ee)
$BRAQUA=rgba(bfffc5ee)
$WHITE=rgba(191914ee)
