$BGCOLOR=rgb(fffbeb)
$FGCOLOR=rgb(1f1f1f)
$BORDER_FOCUS=rgba(1f1f1fee)
$BORDER_NORMAL=rgba(6c664bee)

$BLACK=rgba(fffbebee)
$RED=rgba(cb3a2aee)
$GREEN=rgba(14710aee)
$YELLOW=rgba(846e15ee)
$BLUE=rgba(644ac9ee)
$PURPLE=rgba(a3144dee)
$AQUA=rgba(036a96ee)
$GRAY=rgba(6c664bee)
$BRGRAY=rgba(4c4a3dee)
$BRRED=rgba(d74c3dee)
$BRGREEN=rgba(198d0cee)
$BRYELLOW=rgba(9e841aee)
$BRBLUE=rgba(7862d0ee)
$BRPURPLE=rgba(bf185aee)
$BRAQUA=rgba(047fb4ee)
$WHITE=rgba(2c2b31ee)
