$BGCOLOR=rgb(f5f4f0)
$FGCOLOR=rgb(1f1c16)
$BORDER_FOCUS=rgba(6e6459ee)
$BORDER_NORMAL=rgba(91887dee)

$BLACK=rgba(f5f4f0ee)
$RED=rgba(9e3e3eee)
$GREEN=rgba(387050ee)
$YELLOW=rgba(7d6820ee)
$BLUE=rgba(3468a8ee)
$PURPLE=rgba(6438a0ee)
$AQUA=rgba(287070ee)
$GRAY=rgba(91887dee)
$BRGRAY=rgba(746c62ee)
$BRRED=rgba(9e3e3eee)
$BRGREEN=rgba(387050ee)
$BRYELLOW=rgba(7d6820ee)
$BRBLUE=rgba(3468a8ee)
$BRPURPLE=rgba(6438a0ee)
$BRAQUA=rgba(287070ee)
$WHITE=rgba(fefcfaee)
