$BGCOLOR=rgb(f1e3d1)
$FGCOLOR=rgb(64513e)
$BORDER_FOCUS=rgba(786653ee)
$BORDER_NORMAL=rgba(b5a492ee)

$BLACK=rgba(f1e3d1ee)
$RED=rgba(d09700ee)
$GREEN=rgba(908d6aee)
$YELLOW=rgba(993333ee)
$BLUE=rgba(bf7979ee)
$PURPLE=rgba(9e5581ee)
$AQUA=rgba(d09700ee)
$GRAY=rgba(b5a492ee)
$BRGRAY=rgba(a0907dee)
$BRRED=rgba(d09700ee)
$BRGREEN=rgba(908d6aee)
$BRYELLOW=rgba(993333ee)
$BRBLUE=rgba(bf7979ee)
$BRPURPLE=rgba(9e5581ee)
$BRAQUA=rgba(d09700ee)
$WHITE=rgba(8c7b68ee)
