$BGCOLOR=rgb(242015)
$FGCOLOR=rgb(d2c3a4)
$BORDER_FOCUS=rgba(ebe0bbee)
$BORDER_NORMAL=rgba(5f4e41ee)

$BLACK=rgba(242015ee)
$RED=rgba(db930dee)
$GREEN=rgba(7a7653ee)
$YELLOW=rgba(a82d56ee)
$BLUE=rgba(c1666bee)
$PURPLE=rgba(91506cee)
$AQUA=rgba(db930dee)
$GRAY=rgba(5f4e41ee)
$BRGRAY=rgba(b8a58cee)
$BRRED=rgba(db930dee)
$BRGREEN=rgba(7a7653ee)
$BRYELLOW=rgba(a82d56ee)
$BRBLUE=rgba(c1666bee)
$BRPURPLE=rgba(91506cee)
$BRAQUA=rgba(db930dee)
$WHITE=rgba(f1e9d0ee)
