$BGCOLOR=rgb(dbd6d1)
$FGCOLOR=rgb(433b32)
$BORDER_FOCUS=rgba(2c2620ee)
$BORDER_NORMAL=rgba(8a8075ee)

$BLACK=rgba(dbd6d1ee)
$RED=rgba(826d57ee)
$GREEN=rgba(57826dee)
$YELLOW=rgba(6d8257ee)
$BLUE=rgba(6d5782ee)
$PURPLE=rgba(82576dee)
$AQUA=rgba(576d82ee)
$GRAY=rgba(8a8075ee)
$BRGRAY=rgba(5a5047ee)
$BRRED=rgba(826d57ee)
$BRGREEN=rgba(57826dee)
$BRYELLOW=rgba(6d8257ee)
$BRBLUE=rgba(6d5782ee)
$BRPURPLE=rgba(82576dee)
$BRAQUA=rgba(576d82ee)
$WHITE=rgba(16130fee)
