$BGCOLOR=rgb(fffbef)
$FGCOLOR=rgb(5c6a72)
$BORDER_FOCUS=rgba(414b50ee)
$BORDER_NORMAL=rgba(939f91ee)

$BLACK=rgba(fffbefee)
$RED=rgba(f85552ee)
$GREEN=rgba(8da101ee)
$YELLOW=rgba(dfa000ee)
$BLUE=rgba(3a94c5ee)
$PURPLE=rgba(df69baee)
$AQUA=rgba(35a77cee)
$GRAY=rgba(939f91ee)
$BRGRAY=rgba(829181ee)
$BRRED=rgba(f85552ee)
$BRGREEN=rgba(8da101ee)
$BRYELLOW=rgba(dfa000ee)
$BRBLUE=rgba(3a94c5ee)
$BRPURPLE=rgba(df69baee)
$BRAQUA=rgba(35a77cee)
$WHITE=rgba(272e33ee)
